{"level":"\u001b[31merror\u001b[39m","message":"\u001b[31m数据库连接失败: Access denied for user 'root'@'172.18.0.1' (using password: YES)\u001b[39m","name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'172.18.0.1' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'172.18.0.1' (using password: YES)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'root'@'172.18.0.1' (using password: YES)\n    at ConnectionManager.connect (E:\\mypro\\ai-links\\backend-nodejs\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:94:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ConnectionManager._connect (E:\\mypro\\ai-links\\backend-nodejs\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:222:24)\n    at async E:\\mypro\\ai-links\\backend-nodejs\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (E:\\mypro\\ai-links\\backend-nodejs\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async E:\\mypro\\ai-links\\backend-nodejs\\node_modules\\sequelize\\lib\\sequelize.js:305:26\n    at async Sequelize.authenticate (E:\\mypro\\ai-links\\backend-nodejs\\node_modules\\sequelize\\lib\\sequelize.js:457:5)\n    at async testConnection (E:\\mypro\\ai-links\\backend-nodejs\\config\\database-connection.js:27:5)\n    at async startServer (E:\\mypro\\ai-links\\backend-nodejs\\server.js:18:25)","timestamp":"2025-09-24 21:21:34:2134"}
{"ip":"127.0.0.1","level":"\u001b[31merror\u001b[39m","message":"\u001b[31m错误: Unknown column 'Tool.approved_by' in 'field list'\u001b[39m","method":"GET","stack":"Error\n    at Query.run (E:\\mypro\\ai-links\\backend-nodejs\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n    at E:\\mypro\\ai-links\\backend-nodejs\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async MySQLQueryInterface.select (E:\\mypro\\ai-links\\backend-nodejs\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:407:12)\n    at async Tool.findAll (E:\\mypro\\ai-links\\backend-nodejs\\node_modules\\sequelize\\lib\\model.js:1140:21)\n    at async Promise.all (index 1)\n    at async Tool.findAndCountAll (E:\\mypro\\ai-links\\backend-nodejs\\node_modules\\sequelize\\lib\\model.js:1322:27)\n    at async E:\\mypro\\ai-links\\backend-nodejs\\controllers\\toolsController.js:45:18","timestamp":"2025-09-24 21:27:44:2744","url":"/api/tools?page=1&per_page=10&category=&is_public=&my_tools=false","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"}
{"address":"0.0.0.0","code":"EADDRINUSE","errno":-4091,"level":"\u001b[31merror\u001b[39m","message":"\u001b[31m未捕获的异常: listen EADDRINUSE: address already in use 0.0.0.0:5000\u001b[39m","port":5000,"stack":"Error: listen EADDRINUSE: address already in use 0.0.0.0:5000\n    at Server.setupListenHandle [as _listen2] (node:net:1908:16)\n    at listenInCluster (node:net:1965:12)\n    at doListen (node:net:2139:7)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)","syscall":"listen","timestamp":"2025-09-24 21:33:00:330"}
{"address":"0.0.0.0","code":"EADDRINUSE","errno":-4091,"level":"\u001b[31merror\u001b[39m","message":"\u001b[31m未捕获的异常: listen EADDRINUSE: address already in use 0.0.0.0:5000\u001b[39m","port":5000,"stack":"Error: listen EADDRINUSE: address already in use 0.0.0.0:5000\n    at Server.setupListenHandle [as _listen2] (node:net:1908:16)\n    at listenInCluster (node:net:1965:12)\n    at doListen (node:net:2139:7)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)","syscall":"listen","timestamp":"2025-09-24 21:33:25:3325"}
{"ip":"127.0.0.1","level":"\u001b[31merror\u001b[39m","message":"\u001b[31m错误: Unknown column 'Tool.approved_by' in 'field list'\u001b[39m","method":"GET","stack":"Error\n    at Query.run (E:\\mypro\\ai-links\\backend-nodejs\\node_modules\\sequelize\\lib\\dialects\\mysql\\query.js:52:25)\n    at E:\\mypro\\ai-links\\backend-nodejs\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async MySQLQueryInterface.select (E:\\mypro\\ai-links\\backend-nodejs\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:407:12)\n    at async Tool.findAll (E:\\mypro\\ai-links\\backend-nodejs\\node_modules\\sequelize\\lib\\model.js:1140:21)\n    at async Promise.all (index 1)\n    at async Tool.findAndCountAll (E:\\mypro\\ai-links\\backend-nodejs\\node_modules\\sequelize\\lib\\model.js:1322:27)\n    at async E:\\mypro\\ai-links\\backend-nodejs\\controllers\\toolsController.js:45:18","timestamp":"2025-09-24 21:44:34:4434","url":"/api/tools?page=1&per_page=10&category=&is_public=&my_tools=false","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"}
